
# To run SimTS with pipeline integration on classification task
python3 train_simts.py --dataset ArticularyWordRecognition --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset AtrialFibrillation --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset CharacterTrajectories --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset Cricket --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset DuckDuckGeese --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset EigenWorms --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset Epilepsy --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset EthanolConcentration --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset FaceDetection --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset FingerMovements --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset HandMovementDirection --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset Handwriting --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset Heartbeat --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset Images --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset InsectWingbeat --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset JapaneseVowels --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset Libras --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset LSST --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset MotorImagery --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset NATOPS --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset PEMS-SF --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset PenDigits --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset PhonemeSpectra --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset RacketSports --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset SelfRegulationSCP1 --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset SelfRegulationSCP2 --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset SpokenArabicDigits --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset StandWalkJump --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset UrbanSound --loader UEA --dir training/classification --eval
python3 train_simts.py --dataset UWaveGestureLibrary --loader UEA --dir training/classification --eval

# To run original SimTS model on classification task
python3 script.py --dataset ArticularyWordRecognition --loader UEA --dir training/classification --eval
python3 script.py --dataset AtrialFibrillation --loader UEA --dir training/classification --eval
python3 script.py --dataset CharacterTrajectories --loader UEA --dir training/classification --eval
python3 script.py --dataset Cricket --loader UEA --dir training/classification --eval
python3 script.py --dataset DuckDuckGeese --loader UEA --dir training/classification --eval
python3 script.py --dataset EigenWorms --loader UEA --dir training/classification --eval
python3 script.py --dataset Epilepsy --loader UEA --dir training/classification --eval
python3 script.py --dataset EthanolConcentration --loader UEA --dir training/classification --eval
python3 script.py --dataset FaceDetection --loader UEA --dir training/classification --eval
python3 script.py --dataset FingerMovements --loader UEA --dir training/classification --eval
python3 script.py --dataset HandMovementDirection --loader UEA --dir training/classification --eval
python3 script.py --dataset Handwriting --loader UEA --dir training/classification --eval
python3 script.py --dataset Heartbeat --loader UEA --dir training/classification --eval
python3 script.py --dataset Images --loader UEA --dir training/classification --eval
python3 script.py --dataset InsectWingbeat --loader UEA --dir training/classification --eval
python3 script.py --dataset JapaneseVowels --loader UEA --dir training/classification --eval
python3 script.py --dataset Libras --loader UEA --dir training/classification --eval
python3 script.py --dataset LSST --loader UEA --dir training/classification --eval
python3 script.py --dataset MotorImagery --loader UEA --dir training/classification --eval
python3 script.py --dataset NATOPS --loader UEA --dir training/classification --eval
python3 script.py --dataset PEMS-SF --loader UEA --dir training/classification --eval
python3 script.py --dataset PenDigits --loader UEA --dir training/classification --eval
python3 script.py --dataset PhonemeSpectra --loader UEA --dir training/classification --eval
python3 script.py --dataset RacketSports --loader UEA --dir training/classification --eval
python3 script.py --dataset SelfRegulationSCP1 --loader UEA --dir training/classification --eval
python3 script.py --dataset SelfRegulationSCP2 --loader UEA --dir training/classification --eval
python3 script.py --dataset SpokenArabicDigits --loader UEA --dir training/classification --eval
python3 script.py --dataset StandWalkJump --loader UEA --dir training/classification --eval
python3 script.py --dataset UrbanSound --loader UEA --dir training/classification --eval
python3 script.py --dataset UWaveGestureLibrary --loader UEA --dir training/classification --eval